In [1]:
import torch
import math

In [4]:

mask = torch.triu(torch.ones((1, 5, 5)), diagonal=1).type(torch.int)
mask==0

tensor([[[ True, False, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]]])

In [3]:
seq_len = 4
position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1) # (seq_len, 1)

In [4]:
position

tensor([[0.],
        [1.],
        [2.],
        [3.]])

In [9]:
d_model = 6
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model)) # (d_model / 2)

In [12]:
div_term.unsqueeze(0)

tensor([[1.0000, 0.0464, 0.0022]])

In [13]:
torch.sin(position * div_term.unsqueeze(0))

tensor([[0.0000, 0.0000, 0.0000],
        [0.8415, 0.0464, 0.0022],
        [0.9093, 0.0927, 0.0043],
        [0.1411, 0.1388, 0.0065]])